# See http://docs.travis-ci.com/user/languages/csharp/ for details

# TODO: Test against Mono as well, using matrix.include
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

# We need to install the .NET Core 1.0 runtime to run netcoreapp1.0
# tests.
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

before_script:
- ./prepare.sh
script:
- set -e
- sed -i -e 's/netstandard1.3;net452;xamarinios10;monoandroid44/netstandard1.3/' SharpSnmpLib/SharpSnmpLib.csproj
- sed -i -e 's/netcoreapp1.0;net452/netcoreapp1.0/' Tests/CSharpCore/Tests.NetStandard.csproj
- dotnet build SharpSnmpLib.NetStandard.macOS.sln
- cd Tests
- cd CSharpCore
- dotnet test --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Integration"
- dotnet test --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Unit"
