# See http://docs.travis-ci.com/user/languages/csharp/ for details

language: csharp
mono:
- latest
dotnet: 2.1.3
dist: trusty

# We need to install the .NET Core 1.0 runtime to run netcoreapp1.0
# tests.
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

# xamarinios10 and monoandroid44 are out of build, as not sure if they work.
# net452 is out of testing, as dotnet test does not like it.
before_script:
- ./prepare.sh
script:
- set -e
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- sed -i -e 's/netcoreapp2.0;netstandard1.3;net452;xamarinios10;monoandroid44/netstandard1.3;net452/' SharpSnmpLib/SharpSnmpLib.csproj
- sed -i -e 's/netcoreapp2.0;netcoreapp1.0;net452/netcoreapp1.0/' Tests/CSharpCore/Tests.NetStandard.csproj
- dotnet build SharpSnmpLib.NetStandard.macOS.sln
- cd Tests
- cd CSharpCore
- dotnet test --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Integration.TrapDaemonTestFixture"
- dotnet test --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Integration.DaemonTestFixture"
- dotnet test --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Unit"