version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
  - git submodule update --init --recursive
  - .\prepare.bat
build_script:
  - .\build.release.bat
test_script:
  - dotnet test Tests\CSharpCore\Tests.NetStandard.csproj --no-build --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Integration.TrapDaemonTestFixture"
  - dotnet test Tests\CSharpCore\Tests.NetStandard.csproj --no-build --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Integration.DaemonTestFixture"
  - dotnet test Tests\CSharpCore\Tests.NetStandard.csproj --no-build --filter "FullyQualifiedName~Lextm.SharpSnmpLib.Unit"